service: my-serverless-app

provider:
  name: aws
  runtime: nodejs18.x
  timeout: 30
  stage: ${opt:stage}
  region: ${env:AWS_REGION, 'us-east-1'}
  memorySize: 128
  profile: ${self:custom.profiles.${self:provider.stage}}
  #iamRoleStatements:
    # - Effect: 'Allow'
    #   Action:
    #     - 'lambda:InvokeFunction'
    #     - 'lambda:InvokeAsync'
    #     - 'cognito:*'
    #     - 'sqs:*'
    #     - 's3:*'
    #   Resource: '*'

  environment: ${file(${self:custom.config}):environment}

functions: ${file(${self:custom.functions}):functions}

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  stage: ${opt:stage, self:provider.stage}
  functions: serverless-files/${self:custom.stage}/functions.yml
  config: serverless-files/${self:custom.stage}/config.yml
  fullName: ${self:service}-${self:custom.stage}
  serverless-offline:
    httpPort: 4000
  defaultStage: dev
  profiles:
    dev: dev
    prod: default

package:
  exclude:
    - node_modules/**/aws-sdk/**
    - node_modules/**/aws-lambda/**